# Arrays

In [147]:
import numpy as np
from scipy import sparse

In [148]:
vector_row = np.array([1,2,3])
print(vector_row)

[1 2 3]


In [149]:
vector_column = np.array([[1],
                          [2],
                          [3]])
print(vector_column)

[[1]
 [2]
 [3]]


In [150]:
matrix = np.array([[1,2,3],
                   [3,4,5],
                   [6,7,8]])
print(matrix)

[[1 2 3]
 [3 4 5]
 [6 7 8]]


Below is example of sparse matrix, the results will
show the non-zero position of the matrix and values
in those positions.

In [151]:
matrix = np.array([[1,0,3],
                   [0,4,0],
                   [2,0,0]])
matrix_sparse = sparse.csr_matrix(matrix)
print(matrix_sparse)

  (0, 0)	1
  (0, 2)	3
  (1, 1)	4
  (2, 0)	2


Describing a matrix

In [152]:
matrix = np.array([[1, 2, 3, 4],
                   [5, 6, 7, 8],
                   [9, 10, 11, 12]])

matrix.shape

(3, 4)

In [153]:
matrix.size

12

In [154]:
matrix.ndim
# num of dimensions

2

Applying Operation to elements in Arrays

In [155]:
#Broadcasting 
matrix = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9]])
matrix + 100

array([[101, 102, 103],
       [104, 105, 106],
       [107, 108, 109]])

In [156]:
#Vectorize
# Create matrix
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# Create function that adds 100 to something
add_100 = lambda i: i + 100

# Create vectorized function
vectorized_add_100 = np.vectorize(add_100)

# Apply function to all elements in matrix
vectorized_add_100(matrix)

array([[101, 102, 103],
       [104, 105, 106],
       [107, 108, 109]])

In [157]:
import numpy as np

# Create matrix
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# Return maximum element
np.max(matrix)

9

In [158]:
np.min(matrix)

1

In [159]:
#axix 0 is column
np.max(matrix, axis=0)

array([7, 8, 9])

In [160]:
#axis 1 is row
np.max(matrix, axis=1)

array([3, 6, 9])

# Calculating the Average, Variance, and Standard Deviation
# calculate some descriptive statistics

In [161]:
# Create matrix
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# Return mean
np.mean(matrix)

5.0

In [162]:
# Return variance
np.var(matrix)

6.666666666666667

In [163]:
# Return standard deviation
np.std(matrix)

2.581988897471611

In [164]:
# Find the mean value in each column
np.mean(matrix, axis=0)


array([4., 5., 6.])

In [165]:
#Create 4x3 matrix
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9],
                   [10, 11, 12]])

# Reshape matrix into 2x6 matrix
matrix.reshape(2, 6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [166]:
# One useful argument in reshape is -1, which effectively
# means “as many as needed,” so reshape(1, -1) means
# one row and as many columns as needed:

matrix.reshape(1, -1)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

In [167]:
# will provide an 1D array of that length.
matrix.reshape(12)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [168]:
# Create matrix
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# Transpose matrix
matrix.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [169]:
# However, it is common to refer to transposing a vector
# as converting a row vector to a column vector
# (notice the second pair of brackets) or vice versa:

# Tranpose row vector
np.array([[1, 2, 3, 4, 5, 6]]).T


array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [170]:
# Create matrix
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# Flatten matrix
matrix.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [171]:
# Create matrix
matrix = np.array([[1, 1, 1],
                   [1, 1, 10],
                   [1, 1, 15]])

# Return matrix rank
np.linalg.matrix_rank(matrix)

#The rank of a matrix is the dimensions of the vector
# space spanned by its columns or rows. Finding the rank
# of a matrix is easy in NumPy thanks to matrix_rank.

2

In [172]:
# Create matrix
matrix = np.array([[1, 2, 3],
                   [2, 4, 6],
                   [3, 8, 9]])

# Return determinant of matrix
np.linalg.det(matrix)

# sometimes be useful to calculate the determinant of a matrix.
# NumPy makes this easy with det.

0.0

In [173]:
# Create matrix
matrix = np.array([[1, 2, 3],
                   [2, 4, 6],
                   [3, 8, 9]])

# Return diagonal elements
matrix.diagonal()

array([1, 4, 9])

In [174]:
# Return diagonal one above the main diagonal
matrix.diagonal(offset=1)

array([2, 6])

In [175]:
matrix.diagonal(offset=-1)

array([2, 8])

In [176]:
# Create matrix
matrix = np.array([[1, 2, 3],
                   [2, 4, 6],
                   [3, 8, 9]])

# Return trace
matrix.trace()
#The trace of a matrix is the sum of the diagonal elements

14

In [177]:
#We can also return the diagonal of a matrix and calculate its sum:
# Return diagonal and sum elements
sum(matrix.diagonal())


14

In [178]:
import numpy as np

# Create matrix
matrix = np.array([[1, -1, 3],
                   [1, 1, 6],
                   [3, 8, 9]])

# Calculate eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(matrix)

In [179]:
eigenvalues

array([13.55075847,  0.74003145, -3.29078992])

In [180]:
eigenvectors

array([[-0.17622017, -0.96677403, -0.53373322],
       [-0.435951  ,  0.2053623 , -0.64324848],
       [-0.88254925,  0.15223105,  0.54896288]])

In [181]:
# Create two vectors
vector_a = np.array([1,2,3])
vector_b = np.array([4,5,6])

# Calculate dot product
np.dot(vector_a, vector_b)

32

In [182]:
# Calculate dot product (in Python 3.5+ we can use the new @ operator)
vector_a @ vector_b

32

In [183]:
# Create matrix
matrix_a = np.array([[1, 1, 1],
                     [1, 1, 1],
                     [1, 1, 2]])

# Create matrix
matrix_b = np.array([[1, 3, 1],
                     [1, 3, 1],
                     [1, 3, 8]])

# Add two matrices
np.add(matrix_a, matrix_b)

array([[ 2,  4,  2],
       [ 2,  4,  2],
       [ 2,  4, 10]])

In [184]:
np.subtract(matrix_a, matrix_b)

array([[ 0, -2,  0],
       [ 0, -2,  0],
       [ 0, -2, -6]])

In [185]:
# Add two matrices, Alternatively, we can simply use the + and - operators:
matrix_a + matrix_b

array([[ 2,  4,  2],
       [ 2,  4,  2],
       [ 2,  4, 10]])

In [186]:
# Create matrix
matrix_a = np.array([[1, 1],
                     [1, 2]])

# Create matrix
matrix_b = np.array([[1, 3],
                     [1, 2]])

# Multiply two matrices
np.dot(matrix_a, matrix_b)

array([[2, 5],
       [3, 7]])

In [187]:
# Create matrix
matrix_a = np.array([[1, 1],
                     [1, 2]])

# Create matrix
matrix_b = np.array([[1, 3],
                     [1, 2]])

# Multiply two matrices
np.dot(matrix_a, matrix_b)

array([[2, 5],
       [3, 7]])

In [188]:
# Multiply two matrices, Alternatively, in Python 3.5+ we can use the @ operator:
matrix_a @ matrix_b

array([[2, 5],
       [3, 7]])

In [189]:
# Multiply two matrices element-wise
matrix_a * matrix_b

array([[1, 3],
       [1, 4]])

In [190]:
# Create matrix
matrix = np.array([[1, 4],
                   [2, 5]])

# Calculate inverse of matrix
np.linalg.inv(matrix)

array([[-1.66666667,  1.33333333],
       [ 0.66666667, -0.33333333]])

In [191]:
# Multiply matrix and its inverse
matrix @ np.linalg.inv(matrix)

array([[1.00000000e+00, 0.00000000e+00],
       [1.11022302e-16, 1.00000000e+00]])

In [192]:
# Load library
import numpy as np

# Set seed
np.random.seed(0)

# Generate three random floats between 0.0 and 1.0
np.random.random(3)

array([0.5488135 , 0.71518937, 0.60276338])

In [193]:
# Generate three random integers between 0 and 10
np.random.randint(0, 11, 3)

array([3, 7, 9])

In [194]:
# Draw three numbers from a normal distribution with mean 0.0
# and standard deviation of 1.0
np.random.normal(0.0, 1.0, 3)

array([-1.42232584,  1.52006949, -0.29139398])

In [195]:
np.random.logistic(0.0, 1.0, 3)

array([-0.98118713, -0.08939902,  1.46416405])

In [196]:
np.random.uniform(1.0, 2.0, 3)


array([1.47997717, 1.3927848 , 1.83607876])